#define SETBIT(WORD,BITPOS) (WORD |= (1 << BITPOS))
#define CLRBIT(WORD,BITPOS) (WORD &= (1 << BITPOS))
#define CPLBIT(WORD,BITPOS) (WORD ^= (1 << BITPOS))

#define SCLRBIT(WORD,BITPOS) (WORD = 1 << BITPOS)
#define SSETBIT(WORD,BITPOS) (WORD = 1 << BITPOS)

#define READBIT(WORD,BITPOS)           ((WORD >> BITPOS) & 1)
#define READNIBBLE(WORD,STARTBITPOS)   ((WORD >> STARTBITPOS) & 15)
#define READBYTE(WORD,STARTBITPOS)     ((WORD >> STARTBITPOS) & 255)

#define WRITEBIT(WORD,BITPOS,BIT)              (WORD = ((WORD & ~(1 << BITPOS)) | (BIT << BITPOS)))
#define WRITENIBBLE(WORD,STARTBITPOS,NIBBLE)   (WORD = ((WORD & ~(15 <<STARTBITPOS) | (NIBBLE <<STARTBITPOS))))
#define WRITEBYTE(WORD,STARTBITPOS,BYTE)       (WORD = ((WORD & ~(255 << STARTBITPOS) | (BYTE << STARTBITPOS))))

#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT) DWORD = ((DWORD & ~(1 << DBIT)) | (((SWORD >> SBIT) & 1) << DBIT))




          

